
language: python
matrix:
  include:
  - python: "3.5"
  - python: "nightly"
  allow_failures:
  - python: "nightly"

before_install:
 - "pip install pyinstaller"
 - "pip install PyQt5"

install:
 - "python setup.py install"

script:
 - "./build.sh"
 - "pyinstaller aw-qt.spec"
 - "pyinstaller aw-qt-onefile.spec"
