language: python
matrix:
  include:
  - python: "3.5"
  - python: "nightly"
  allow_failures:
  - python: "nightly"

before_install:
 - "pip install pyinstaller"
 - "pip install PyQt5"

install:
 - "make build"

script:
 - "python -c 'import aw_qt'"
 - "make package"

