
language: python
python:
# - "3.3"
# - "3.4"
 - "3.5"
 - "nightly" # currently points to 3.6-dev

before_install:
 - "pip install pyqt5"

install:
 - "python setup.py install"

script:
 - "./build.sh"
 - "true"
