dist: trusty

language: python
matrix:
  include:
  - python: "3.5"
  - python: "3.6"
  - python: "nightly"
  - os: osx
    language: generic
    env: PYENV_VERSION='3.6.5' PYTHON_CONFIGURE_OPTS="--enable-framework"
  allow_failures:
  - python: "nightly"

before_install:
 - |
     if [[ -n "$PYENV_VERSION" ]]; then
       wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.4.0/setup-pyenv.sh
       source setup-pyenv.sh
     fi
   # We might want to move this into the integration test script
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
     export DISPLAY=:99.0;
     sh -e /etc/init.d/xvfb start;
     sleep 3;
   fi
 - python -V
 - pip -V
 - pip3 install --upgrade pip
 - pip3 install pyinstaller

install:
 - make build

script:
 - make typecheck
 - make test
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
     make test-integration;
   fi
 - make package

