language: python
matrix:
  include:
  - python: "3.5"
  - python: "nightly"
  - os: osx
    language: generic
  allow_failures:
  - python: "nightly"

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
     wget https://github.com/ActivityWatch/activitywatch/raw/master/scripts/ci/setup_venv_osx.sh;
     chmod +x setup_venv_osx.sh;
     ./setup_venv_osx.sh
     source venv/bin/activate;
   fi
   # We might want to move this into the integration test script
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
     export DISPLAY=:99.0;
     sh -e /etc/init.d/xvfb start;
     sleep 3;
   fi
 - pip install --upgrade pip
 - pip install pyinstaller
   # Installing with `pip install pyqt5` doesn't work reliably for whatever reason.
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
     pip install https://pypi.python.org/packages/0f/a8/71d918272a9ae17541942daffb15d663d7c9401346252a495a84822e81d5/PyQt5-5.8.2-5.8.0-cp35.cp36.cp37-abi3-macosx_10_6_intel.whl
   fi

install:
 - make build

script:
 - make test
 - make test-integration
 - make package

