name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macOS-11]
        python_version: [3.9]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install APT dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y qt5-default libfontconfig1
    - name: Install dependencies
      shell: bash
      run: |
        pip install poetry==1.3.2
        python -m venv venv
        source venv/bin/activate || source venv/Scripts/activate
        poetry install
    - name: Build
      shell: bash
      run: |
        source venv/bin/activate || source venv/Scripts/activate
        make build
    - name: Run tests
      shell: bash
      run: |
        source venv/bin/activate || source venv/Scripts/activate
        make test
        make typecheck
    - name: Run integration tests
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y xvfb
        source venv/bin/activate || source venv/Scripts/activate
        env QT_DEBUG_PLUGINS=true xvfb-run --auto-servernum make test-integration;
    - name: Package
      shell: bash
      run: |
        source venv/bin/activate || source venv/Scripts/activate
        make package
    - name: Upload package
      uses: actions/upload-artifact@v2-preview
      with:
        name: builds-${{ runner.os }}-py${{ matrix.python_version }}
        path: dist/aw-qt
